name: Build & Test NLog.Loki

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install Dependencies
      run: dotnet restore .\\src\\NLog.Loki.sln
    - name: Build
      run: dotnet build .\\src\\NLog.Loki.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test .\\src\\NLog.Loki.sln --no-build --verbosity normal
