name: Publish

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Publish NuGet Package

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install Dependencies
      run: dotnet restore .\\src\\NLog.Loki.sln
    - name: Build
      run: dotnet build .\\src\\NLog.Loki.sln --configuration Release --no-restore
    - name: Package
      run: dotnet pack .\\src\\NLog.Loki\\NLog.Loki.csproj --no-restore --output .
    - name: Publish
      id: publish
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ./src/NLog.Loki/NLog.Loki.csproj
        VERSION_FILE_PATH: ./.semver
        VERSION_REGEX: ^(.*)$
        NUGET_KEY: ${{secrets.NUGET_KEY}}
